# Generated by Django 3.2.7 on 2021-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
    ]
