# Generated by Django 3.2.7 on 2021-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=10)),
                ('data', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=1)),
                ('empresa', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
