# Generated by Django 3.2.7 on 2021-09-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=10)),
                ('dataIda', models.CharField(max_length=10)),
                ('dataVolta', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=1)),
                ('empresa', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='descricao',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
