# Generated by Django 3.2.7 on 2021-09-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210926_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='descricao',
        ),
    ]
