# Generated by Django 3.2.7 on 2021-09-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_empresas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacotes',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresas'),
        ),
    ]
