# Generated by Django 3.2.7 on 2021-09-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pacotes_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacotes',
            old_name='dataIda',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='pacotes',
            name='dataVolta',
        ),
        migrations.RemoveField(
            model_name='pacotes',
            name='dias',
        ),
    ]
