# Generated by Django 3.2.7 on 2021-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210926_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='id',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
