# Generated by Django 3.2.7 on 2021-09-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210926_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
