# Generated by Django 3.2.7 on 2021-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210926_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
